sonar.projectKey=steamlink-backend
sonar.projectName=SteamLink Backend
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js
sonar.tests=.
sonar.test.inclusions=**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.host.url=http://localhost:9000
sonar.token=sqa_f757b136f5e325145e6f5cf475701fa7429ece24